services:
  db:
    container_name: postgres_db
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: python_db
    build: .
    command: ["sh", "docker-entrypoint.sh"]
    volumes:
      - .:/backend

volumes:
  db:
    driver: local
